// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: achievemilestone.proto

#include "achievemilestone.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
//PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr DT_achievemilestone::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        icon_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_score_{0u},
        item_type_{0u},
        count_{0u},
        lev_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DT_achievemilestone::DT_achievemilestone(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DT_achievemilestoneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DT_achievemilestoneDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DT_achievemilestoneDefaultTypeInternal() {}
  union {
    DT_achievemilestone _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DT_achievemilestoneDefaultTypeInternal _DT_achievemilestone_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR achievemilestone_ConfigEntry_DoNotUse::achievemilestone_ConfigEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal() {}
  union {
    achievemilestone_ConfigEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal _achievemilestone_ConfigEntry_DoNotUse_default_instance_;

inline constexpr achievemilestone::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR achievemilestone::achievemilestone(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct achievemilestoneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR achievemilestoneDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~achievemilestoneDefaultTypeInternal() {}
  union {
    achievemilestone _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 achievemilestoneDefaultTypeInternal _achievemilestone_default_instance_;
static ::_pb::Metadata file_level_metadata_achievemilestone_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_achievemilestone_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_achievemilestone_2eproto = nullptr;
const ::uint32_t TableStruct_achievemilestone_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.id_score_),
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.icon_),
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.item_type_),
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.count_),
    PROTOBUF_FIELD_OFFSET(::DT_achievemilestone, _impl_.lev_),
    PROTOBUF_FIELD_OFFSET(::achievemilestone_ConfigEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::achievemilestone_ConfigEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::achievemilestone_ConfigEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::achievemilestone_ConfigEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::achievemilestone, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::achievemilestone, _impl_.config_),
};

static const ::_pbi::MigrationSchema
    schemas_achievemilestone[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::DT_achievemilestone)},
        {14, 24, -1, sizeof(::achievemilestone_ConfigEntry_DoNotUse)},
        {26, -1, -1, sizeof(::achievemilestone)},
};

static const ::_pb::Message* const file_default_instances_achievemilestone[] = {
    &::_DT_achievemilestone_default_instance_._instance,
    &::_achievemilestone_ConfigEntry_DoNotUse_default_instance_._instance,
    &::_achievemilestone_default_instance_._instance,
};
const char descriptor_table_protodef_achievemilestone_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\026achievemilestone.proto\"r\n\023DT_achievemi"
    "lestone\022\020\n\010id_score\030\001 \001(\r\022\014\n\004name\030\002 \001(\014\022"
    "\014\n\004icon\030\003 \001(\014\022\021\n\titem_type\030\004 \001(\r\022\r\n\005coun"
    "t\030\005 \001(\r\022\013\n\003lev\030\006 \001(\r\"\206\001\n\020achievemileston"
    "e\022-\n\006config\030\001 \003(\0132\035.achievemilestone.Con"
    "figEntry\032C\n\013ConfigEntry\022\013\n\003key\030\001 \001(\r\022#\n\005"
    "value\030\002 \001(\0132\024.DT_achievemilestone:\0028\001b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_achievemilestone_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_achievemilestone_2eproto = {
    false,
    false,
    285,
    descriptor_table_protodef_achievemilestone_2eproto,
    "achievemilestone.proto",
    &descriptor_table_achievemilestone_2eproto_once,
    nullptr,
    0,
    3,
    schemas_achievemilestone,
    file_default_instances_achievemilestone,
    TableStruct_achievemilestone_2eproto::offsets,
    file_level_metadata_achievemilestone_2eproto,
    file_level_enum_descriptors_achievemilestone_2eproto,
    file_level_service_descriptors_achievemilestone_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_achievemilestone_2eproto_getter() {
  return &descriptor_table_achievemilestone_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_achievemilestone_2eproto(&descriptor_table_achievemilestone_2eproto);
// ===================================================================

class DT_achievemilestone::_Internal {
 public:
};

DT_achievemilestone::DT_achievemilestone(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DT_achievemilestone)
}
inline PROTOBUF_NDEBUG_INLINE DT_achievemilestone::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        icon_(arena, from.icon_),
        _cached_size_{0} {}

DT_achievemilestone::DT_achievemilestone(
    ::google::protobuf::Arena* arena,
    const DT_achievemilestone& from)
    : ::google::protobuf::Message(arena) {
  DT_achievemilestone* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_score_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_score_),
           offsetof(Impl_, lev_) -
               offsetof(Impl_, id_score_) +
               sizeof(Impl_::lev_));

  // @@protoc_insertion_point(copy_constructor:DT_achievemilestone)
}
inline PROTOBUF_NDEBUG_INLINE DT_achievemilestone::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        icon_(arena),
        _cached_size_{0} {}

inline void DT_achievemilestone::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_score_),
           0,
           offsetof(Impl_, lev_) -
               offsetof(Impl_, id_score_) +
               sizeof(Impl_::lev_));
}
DT_achievemilestone::~DT_achievemilestone() {
  // @@protoc_insertion_point(destructor:DT_achievemilestone)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DT_achievemilestone::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.icon_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DT_achievemilestone::Clear() {
// @@protoc_insertion_point(message_clear_start:DT_achievemilestone)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.icon_.ClearToEmpty();
  ::memset(&_impl_.id_score_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.lev_) -
      reinterpret_cast<char*>(&_impl_.id_score_)) + sizeof(_impl_.lev_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DT_achievemilestone::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 0, 2> DT_achievemilestone::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DT_achievemilestone_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 id_score = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achievemilestone, _impl_.id_score_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.id_score_)}},
    // bytes name = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.name_)}},
    // bytes icon = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.icon_)}},
    // uint32 item_type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achievemilestone, _impl_.item_type_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.item_type_)}},
    // uint32 count = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achievemilestone, _impl_.count_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.count_)}},
    // uint32 lev = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achievemilestone, _impl_.lev_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.lev_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id_score = 1;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.id_score_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bytes name = 2;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes icon = 3;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.icon_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 item_type = 4;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.item_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 count = 5;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 lev = 6;
    {PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.lev_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DT_achievemilestone::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DT_achievemilestone)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id_score = 1;
  if (this->_internal_id_score() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id_score(), target);
  }

  // bytes name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // bytes icon = 3;
  if (!this->_internal_icon().empty()) {
    const std::string& _s = this->_internal_icon();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // uint32 item_type = 4;
  if (this->_internal_item_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_item_type(), target);
  }

  // uint32 count = 5;
  if (this->_internal_count() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_count(), target);
  }

  // uint32 lev = 6;
  if (this->_internal_lev() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_lev(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DT_achievemilestone)
  return target;
}

::size_t DT_achievemilestone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DT_achievemilestone)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_name());
  }

  // bytes icon = 3;
  if (!this->_internal_icon().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_icon());
  }

  // uint32 id_score = 1;
  if (this->_internal_id_score() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id_score());
  }

  // uint32 item_type = 4;
  if (this->_internal_item_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_item_type());
  }

  // uint32 count = 5;
  if (this->_internal_count() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_count());
  }

  // uint32 lev = 6;
  if (this->_internal_lev() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_lev());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DT_achievemilestone::_class_data_ = {
    DT_achievemilestone::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DT_achievemilestone::GetClassData() const {
  return &_class_data_;
}

void DT_achievemilestone::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DT_achievemilestone*>(&to_msg);
  auto& from = static_cast<const DT_achievemilestone&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DT_achievemilestone)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_icon().empty()) {
    _this->_internal_set_icon(from._internal_icon());
  }
  if (from._internal_id_score() != 0) {
    _this->_internal_set_id_score(from._internal_id_score());
  }
  if (from._internal_item_type() != 0) {
    _this->_internal_set_item_type(from._internal_item_type());
  }
  if (from._internal_count() != 0) {
    _this->_internal_set_count(from._internal_count());
  }
  if (from._internal_lev() != 0) {
    _this->_internal_set_lev(from._internal_lev());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DT_achievemilestone::CopyFrom(const DT_achievemilestone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DT_achievemilestone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DT_achievemilestone::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DT_achievemilestone::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DT_achievemilestone::InternalSwap(DT_achievemilestone* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.icon_, &other->_impl_.icon_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.lev_)
      + sizeof(DT_achievemilestone::_impl_.lev_)
      - PROTOBUF_FIELD_OFFSET(DT_achievemilestone, _impl_.id_score_)>(
          reinterpret_cast<char*>(&_impl_.id_score_),
          reinterpret_cast<char*>(&other->_impl_.id_score_));
}

::google::protobuf::Metadata DT_achievemilestone::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achievemilestone_2eproto_getter, &descriptor_table_achievemilestone_2eproto_once,
      file_level_metadata_achievemilestone_2eproto[0]);
}
// ===================================================================

achievemilestone_ConfigEntry_DoNotUse::achievemilestone_ConfigEntry_DoNotUse() {}
achievemilestone_ConfigEntry_DoNotUse::achievemilestone_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata achievemilestone_ConfigEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achievemilestone_2eproto_getter, &descriptor_table_achievemilestone_2eproto_once,
      file_level_metadata_achievemilestone_2eproto[1]);
}
// ===================================================================

class achievemilestone::_Internal {
 public:
};

achievemilestone::achievemilestone(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:achievemilestone)
}
inline PROTOBUF_NDEBUG_INLINE achievemilestone::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : config_{visibility, arena, from.config_},
        _cached_size_{0} {}

achievemilestone::achievemilestone(
    ::google::protobuf::Arena* arena,
    const achievemilestone& from)
    : ::google::protobuf::Message(arena) {
  achievemilestone* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:achievemilestone)
}
inline PROTOBUF_NDEBUG_INLINE achievemilestone::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : config_{visibility, arena},
        _cached_size_{0} {}

inline void achievemilestone::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
achievemilestone::~achievemilestone() {
  // @@protoc_insertion_point(destructor:achievemilestone)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void achievemilestone::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void achievemilestone::Clear() {
// @@protoc_insertion_point(message_clear_start:achievemilestone)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* achievemilestone::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2> achievemilestone::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_achievemilestone_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<uint32, .DT_achievemilestone> config = 1;
    {PROTOBUF_FIELD_OFFSET(achievemilestone, _impl_.config_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(achievemilestone()._impl_.config_)>(
        1, 0, 0, 13,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::DT_achievemilestone>},
  }}, {{
  }},
};

::uint8_t* achievemilestone::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:achievemilestone)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<uint32, .DT_achievemilestone> config = 1;
  if (!_internal_config().empty()) {
    using MapType = ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>;
    using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::DT_achievemilestone,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_config();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:achievemilestone)
  return target;
}

::size_t achievemilestone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:achievemilestone)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, .DT_achievemilestone> config = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_config_size());
  for (const auto& entry : _internal_config()) {
    total_size += _pbi::MapEntryFuncs<::uint32_t, ::DT_achievemilestone,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData achievemilestone::_class_data_ = {
    achievemilestone::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* achievemilestone::GetClassData() const {
  return &_class_data_;
}

void achievemilestone::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<achievemilestone*>(&to_msg);
  auto& from = static_cast<const achievemilestone&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:achievemilestone)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.config_.MergeFrom(from._impl_.config_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void achievemilestone::CopyFrom(const achievemilestone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:achievemilestone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool achievemilestone::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* achievemilestone::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void achievemilestone::InternalSwap(achievemilestone* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.config_.InternalSwap(&other->_impl_.config_);
}

::google::protobuf::Metadata achievemilestone::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achievemilestone_2eproto_getter, &descriptor_table_achievemilestone_2eproto_once,
      file_level_metadata_achievemilestone_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
