// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        if (hasProperty("USE_INLAND_IMAGE") && USE_INLAND_IMAGE as boolean) {
            println("use inland image")
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/jcenter" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        } else {
            google()
            mavenCentral()
            jcenter()
        }
    }
    dependencies {
        // 更新这个版本，与Gradle 6.7.1兼容
        classpath "com.android.tools.build:gradle:4.2.2"
    }
}

allprojects {
    repositories {
        if (hasProperty("USE_INLAND_IMAGE") && USE_INLAND_IMAGE as boolean) {
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/jcenter" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        } else {
            google()
            mavenCentral()
            jcenter()
        }
    }
}