// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        if (hasProperty("USE_INLAND_IMAGE") && USE_INLAND_IMAGE as boolean) {
            println("use inland image")
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/jcenter" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
            maven { url 'https://maven.qq.com/repository/public/' }
        } else {
            google()
            mavenCentral()
            jcenter()
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath 'com.tencent.bugly:symtabfileuploader:2.2.1'
    }
}

allprojects {
    repositories {
        if (hasProperty("USE_INLAND_IMAGE") && USE_INLAND_IMAGE as boolean) {
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/jcenter" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
            maven { url 'https://maven.qq.com/repository/public/' }
        } else {
            google()
            mavenCentral()
            jcenter()
        }
    }
}