// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: achievemilestone.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_achievemilestone_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_achievemilestone_2eproto_2epb_2eh

#include "ProtobufExport.h"
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_achievemilestone_2eproto PROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct PROTOBUF_API TableStruct_achievemilestone_2eproto {
  static const ::uint32_t offsets[];
};
PROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_achievemilestone_2eproto;
class DT_achievemilestone;
struct DT_achievemilestoneDefaultTypeInternal;
PROTOBUF_API extern DT_achievemilestoneDefaultTypeInternal _DT_achievemilestone_default_instance_;
class achievemilestone;
struct achievemilestoneDefaultTypeInternal;
PROTOBUF_API extern achievemilestoneDefaultTypeInternal _achievemilestone_default_instance_;
class achievemilestone_ConfigEntry_DoNotUse;
struct achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal;
PROTOBUF_API extern achievemilestone_ConfigEntry_DoNotUseDefaultTypeInternal _achievemilestone_ConfigEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_API DT_achievemilestone final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DT_achievemilestone) */ {
 public:
  inline DT_achievemilestone() : DT_achievemilestone(nullptr) {}
  ~DT_achievemilestone() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DT_achievemilestone(::google::protobuf::internal::ConstantInitialized);

  inline DT_achievemilestone(const DT_achievemilestone& from)
      : DT_achievemilestone(nullptr, from) {}
  DT_achievemilestone(DT_achievemilestone&& from) noexcept
    : DT_achievemilestone() {
    *this = ::std::move(from);
  }

  inline DT_achievemilestone& operator=(const DT_achievemilestone& from) {
    CopyFrom(from);
    return *this;
  }
  inline DT_achievemilestone& operator=(DT_achievemilestone&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DT_achievemilestone& default_instance() {
    return *internal_default_instance();
  }
  static inline const DT_achievemilestone* internal_default_instance() {
    return reinterpret_cast<const DT_achievemilestone*>(
               &_DT_achievemilestone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DT_achievemilestone& a, DT_achievemilestone& b) {
    a.Swap(&b);
  }
  inline void Swap(DT_achievemilestone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DT_achievemilestone* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DT_achievemilestone* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DT_achievemilestone>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DT_achievemilestone& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DT_achievemilestone& from) {
    DT_achievemilestone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DT_achievemilestone* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "DT_achievemilestone";
  }
  protected:
  explicit DT_achievemilestone(::google::protobuf::Arena* arena);
  DT_achievemilestone(::google::protobuf::Arena* arena, const DT_achievemilestone& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIconFieldNumber = 3,
    kIdScoreFieldNumber = 1,
    kItemTypeFieldNumber = 4,
    kCountFieldNumber = 5,
    kLevFieldNumber = 6,
  };
  // bytes name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // bytes icon = 3;
  void clear_icon() ;
  const std::string& icon() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_icon(Arg_&& arg, Args_... args);
  std::string* mutable_icon();
  PROTOBUF_NODISCARD std::string* release_icon();
  void set_allocated_icon(std::string* value);

  private:
  const std::string& _internal_icon() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_icon(
      const std::string& value);
  std::string* _internal_mutable_icon();

  public:
  // uint32 id_score = 1;
  void clear_id_score() ;
  ::uint32_t id_score() const;
  void set_id_score(::uint32_t value);

  private:
  ::uint32_t _internal_id_score() const;
  void _internal_set_id_score(::uint32_t value);

  public:
  // uint32 item_type = 4;
  void clear_item_type() ;
  ::uint32_t item_type() const;
  void set_item_type(::uint32_t value);

  private:
  ::uint32_t _internal_item_type() const;
  void _internal_set_item_type(::uint32_t value);

  public:
  // uint32 count = 5;
  void clear_count() ;
  ::uint32_t count() const;
  void set_count(::uint32_t value);

  private:
  ::uint32_t _internal_count() const;
  void _internal_set_count(::uint32_t value);

  public:
  // uint32 lev = 6;
  void clear_lev() ;
  ::uint32_t lev() const;
  void set_lev(::uint32_t value);

  private:
  ::uint32_t _internal_lev() const;
  void _internal_set_lev(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DT_achievemilestone)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr icon_;
    ::uint32_t id_score_;
    ::uint32_t item_type_;
    ::uint32_t count_;
    ::uint32_t lev_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_achievemilestone_2eproto;
};// -------------------------------------------------------------------

class achievemilestone_ConfigEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          achievemilestone_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achievemilestone,
          ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      achievemilestone_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achievemilestone,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  achievemilestone_ConfigEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR achievemilestone_ConfigEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit achievemilestone_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const achievemilestone_ConfigEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const achievemilestone_ConfigEntry_DoNotUse*>(
        &_achievemilestone_ConfigEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_achievemilestone_2eproto;
};
// -------------------------------------------------------------------

class PROTOBUF_API achievemilestone final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:achievemilestone) */ {
 public:
  inline achievemilestone() : achievemilestone(nullptr) {}
  ~achievemilestone() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR achievemilestone(::google::protobuf::internal::ConstantInitialized);

  inline achievemilestone(const achievemilestone& from)
      : achievemilestone(nullptr, from) {}
  achievemilestone(achievemilestone&& from) noexcept
    : achievemilestone() {
    *this = ::std::move(from);
  }

  inline achievemilestone& operator=(const achievemilestone& from) {
    CopyFrom(from);
    return *this;
  }
  inline achievemilestone& operator=(achievemilestone&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const achievemilestone& default_instance() {
    return *internal_default_instance();
  }
  static inline const achievemilestone* internal_default_instance() {
    return reinterpret_cast<const achievemilestone*>(
               &_achievemilestone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(achievemilestone& a, achievemilestone& b) {
    a.Swap(&b);
  }
  inline void Swap(achievemilestone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(achievemilestone* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  achievemilestone* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<achievemilestone>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const achievemilestone& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const achievemilestone& from) {
    achievemilestone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(achievemilestone* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "achievemilestone";
  }
  protected:
  explicit achievemilestone(::google::protobuf::Arena* arena);
  achievemilestone(::google::protobuf::Arena* arena, const achievemilestone& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
  };
  // map<uint32, .DT_achievemilestone> config = 1;
  int config_size() const;
  private:
  int _internal_config_size() const;

  public:
  void clear_config() ;
  const ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>& config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>* mutable_config();

  private:
  const ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>& _internal_config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>* _internal_mutable_config();

  public:
  // @@protoc_insertion_point(class_scope:achievemilestone)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<achievemilestone_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achievemilestone,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        config_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_achievemilestone_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DT_achievemilestone

// uint32 id_score = 1;
inline void DT_achievemilestone::clear_id_score() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_score_ = 0u;
}
inline ::uint32_t DT_achievemilestone::id_score() const {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.id_score)
  return _internal_id_score();
}
inline void DT_achievemilestone::set_id_score(::uint32_t value) {
  _internal_set_id_score(value);
  // @@protoc_insertion_point(field_set:DT_achievemilestone.id_score)
}
inline ::uint32_t DT_achievemilestone::_internal_id_score() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_score_;
}
inline void DT_achievemilestone::_internal_set_id_score(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_score_ = value;
}

// bytes name = 2;
inline void DT_achievemilestone::clear_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& DT_achievemilestone::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DT_achievemilestone::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DT_achievemilestone.name)
}
inline std::string* DT_achievemilestone::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:DT_achievemilestone.name)
  return _s;
}
inline const std::string& DT_achievemilestone::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void DT_achievemilestone::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* DT_achievemilestone::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* DT_achievemilestone::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DT_achievemilestone.name)
  return _impl_.name_.Release();
}
inline void DT_achievemilestone::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DT_achievemilestone.name)
}

// bytes icon = 3;
inline void DT_achievemilestone::clear_icon() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.icon_.ClearToEmpty();
}
inline const std::string& DT_achievemilestone::icon() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.icon)
  return _internal_icon();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DT_achievemilestone::set_icon(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.icon_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DT_achievemilestone.icon)
}
inline std::string* DT_achievemilestone::mutable_icon() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_icon();
  // @@protoc_insertion_point(field_mutable:DT_achievemilestone.icon)
  return _s;
}
inline const std::string& DT_achievemilestone::_internal_icon() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.icon_.Get();
}
inline void DT_achievemilestone::_internal_set_icon(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.icon_.Set(value, GetArena());
}
inline std::string* DT_achievemilestone::_internal_mutable_icon() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.icon_.Mutable( GetArena());
}
inline std::string* DT_achievemilestone::release_icon() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:DT_achievemilestone.icon)
  return _impl_.icon_.Release();
}
inline void DT_achievemilestone::set_allocated_icon(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.icon_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.icon_.IsDefault()) {
          _impl_.icon_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DT_achievemilestone.icon)
}

// uint32 item_type = 4;
inline void DT_achievemilestone::clear_item_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.item_type_ = 0u;
}
inline ::uint32_t DT_achievemilestone::item_type() const {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.item_type)
  return _internal_item_type();
}
inline void DT_achievemilestone::set_item_type(::uint32_t value) {
  _internal_set_item_type(value);
  // @@protoc_insertion_point(field_set:DT_achievemilestone.item_type)
}
inline ::uint32_t DT_achievemilestone::_internal_item_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.item_type_;
}
inline void DT_achievemilestone::_internal_set_item_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.item_type_ = value;
}

// uint32 count = 5;
inline void DT_achievemilestone::clear_count() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.count_ = 0u;
}
inline ::uint32_t DT_achievemilestone::count() const {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.count)
  return _internal_count();
}
inline void DT_achievemilestone::set_count(::uint32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:DT_achievemilestone.count)
}
inline ::uint32_t DT_achievemilestone::_internal_count() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.count_;
}
inline void DT_achievemilestone::_internal_set_count(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.count_ = value;
}

// uint32 lev = 6;
inline void DT_achievemilestone::clear_lev() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.lev_ = 0u;
}
inline ::uint32_t DT_achievemilestone::lev() const {
  // @@protoc_insertion_point(field_get:DT_achievemilestone.lev)
  return _internal_lev();
}
inline void DT_achievemilestone::set_lev(::uint32_t value) {
  _internal_set_lev(value);
  // @@protoc_insertion_point(field_set:DT_achievemilestone.lev)
}
inline ::uint32_t DT_achievemilestone::_internal_lev() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.lev_;
}
inline void DT_achievemilestone::_internal_set_lev(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.lev_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// achievemilestone

// map<uint32, .DT_achievemilestone> config = 1;
inline int achievemilestone::_internal_config_size() const {
  return _internal_config().size();
}
inline int achievemilestone::config_size() const {
  return _internal_config_size();
}
inline void achievemilestone::clear_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.config_.Clear();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>& achievemilestone::_internal_config() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.config_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>& achievemilestone::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:achievemilestone.config)
  return _internal_config();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>* achievemilestone::_internal_mutable_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.config_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_achievemilestone>* achievemilestone::mutable_config() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:achievemilestone.config)
  return _internal_mutable_config();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_achievemilestone_2eproto_2epb_2eh
