// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: achiveactivityshop.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_achiveactivityshop_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_achiveactivityshop_2eproto_2epb_2eh

#include "ProtobufExport.h"
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_achiveactivityshop_2eproto PROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct PROTOBUF_API TableStruct_achiveactivityshop_2eproto {
  static const ::uint32_t offsets[];
};
PROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_achiveactivityshop_2eproto;
class DT_achiveactivityshop;
struct DT_achiveactivityshopDefaultTypeInternal;
PROTOBUF_API extern DT_achiveactivityshopDefaultTypeInternal _DT_achiveactivityshop_default_instance_;
class achiveactivityshop;
struct achiveactivityshopDefaultTypeInternal;
PROTOBUF_API extern achiveactivityshopDefaultTypeInternal _achiveactivityshop_default_instance_;
class achiveactivityshop_ConfigEntry_DoNotUse;
struct achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal;
PROTOBUF_API extern achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal _achiveactivityshop_ConfigEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_API DT_achiveactivityshop final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DT_achiveactivityshop) */ {
 public:
  inline DT_achiveactivityshop() : DT_achiveactivityshop(nullptr) {}
  ~DT_achiveactivityshop() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DT_achiveactivityshop(::google::protobuf::internal::ConstantInitialized);

  inline DT_achiveactivityshop(const DT_achiveactivityshop& from)
      : DT_achiveactivityshop(nullptr, from) {}
  DT_achiveactivityshop(DT_achiveactivityshop&& from) noexcept
    : DT_achiveactivityshop() {
    *this = ::std::move(from);
  }

  inline DT_achiveactivityshop& operator=(const DT_achiveactivityshop& from) {
    CopyFrom(from);
    return *this;
  }
  inline DT_achiveactivityshop& operator=(DT_achiveactivityshop&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DT_achiveactivityshop& default_instance() {
    return *internal_default_instance();
  }
  static inline const DT_achiveactivityshop* internal_default_instance() {
    return reinterpret_cast<const DT_achiveactivityshop*>(
               &_DT_achiveactivityshop_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DT_achiveactivityshop& a, DT_achiveactivityshop& b) {
    a.Swap(&b);
  }
  inline void Swap(DT_achiveactivityshop* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DT_achiveactivityshop* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DT_achiveactivityshop* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DT_achiveactivityshop>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DT_achiveactivityshop& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DT_achiveactivityshop& from) {
    DT_achiveactivityshop::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DT_achiveactivityshop* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "DT_achiveactivityshop";
  }
  protected:
  explicit DT_achiveactivityshop(::google::protobuf::Arena* arena);
  DT_achiveactivityshop(::google::protobuf::Arena* arena, const DT_achiveactivityshop& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kItemIdFieldNumber = 2,
    kShopTypeFieldNumber = 3,
    kReqTypeFieldNumber = 4,
    kEventIdFieldNumber = 5,
    kReq1FieldNumber = 6,
    kReq2FieldNumber = 7,
    kPriceTypeFieldNumber = 8,
    kPriceFieldNumber = 9,
    kLimitTypeFieldNumber = 10,
    kLimitAmountFieldNumber = 11,
  };
  // uint32 id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 item_id = 2;
  void clear_item_id() ;
  ::uint32_t item_id() const;
  void set_item_id(::uint32_t value);

  private:
  ::uint32_t _internal_item_id() const;
  void _internal_set_item_id(::uint32_t value);

  public:
  // uint32 shop_type = 3;
  void clear_shop_type() ;
  ::uint32_t shop_type() const;
  void set_shop_type(::uint32_t value);

  private:
  ::uint32_t _internal_shop_type() const;
  void _internal_set_shop_type(::uint32_t value);

  public:
  // uint32 req_type = 4;
  void clear_req_type() ;
  ::uint32_t req_type() const;
  void set_req_type(::uint32_t value);

  private:
  ::uint32_t _internal_req_type() const;
  void _internal_set_req_type(::uint32_t value);

  public:
  // uint32 event_id = 5;
  void clear_event_id() ;
  ::uint32_t event_id() const;
  void set_event_id(::uint32_t value);

  private:
  ::uint32_t _internal_event_id() const;
  void _internal_set_event_id(::uint32_t value);

  public:
  // uint32 req_1 = 6;
  void clear_req_1() ;
  ::uint32_t req_1() const;
  void set_req_1(::uint32_t value);

  private:
  ::uint32_t _internal_req_1() const;
  void _internal_set_req_1(::uint32_t value);

  public:
  // uint32 req_2 = 7;
  void clear_req_2() ;
  ::uint32_t req_2() const;
  void set_req_2(::uint32_t value);

  private:
  ::uint32_t _internal_req_2() const;
  void _internal_set_req_2(::uint32_t value);

  public:
  // uint32 price_type = 8;
  void clear_price_type() ;
  ::uint32_t price_type() const;
  void set_price_type(::uint32_t value);

  private:
  ::uint32_t _internal_price_type() const;
  void _internal_set_price_type(::uint32_t value);

  public:
  // uint32 price = 9;
  void clear_price() ;
  ::uint32_t price() const;
  void set_price(::uint32_t value);

  private:
  ::uint32_t _internal_price() const;
  void _internal_set_price(::uint32_t value);

  public:
  // uint32 limit_type = 10;
  void clear_limit_type() ;
  ::uint32_t limit_type() const;
  void set_limit_type(::uint32_t value);

  private:
  ::uint32_t _internal_limit_type() const;
  void _internal_set_limit_type(::uint32_t value);

  public:
  // uint32 limit_amount = 11;
  void clear_limit_amount() ;
  ::uint32_t limit_amount() const;
  void set_limit_amount(::uint32_t value);

  private:
  ::uint32_t _internal_limit_amount() const;
  void _internal_set_limit_amount(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DT_achiveactivityshop)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 11, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint32_t id_;
    ::uint32_t item_id_;
    ::uint32_t shop_type_;
    ::uint32_t req_type_;
    ::uint32_t event_id_;
    ::uint32_t req_1_;
    ::uint32_t req_2_;
    ::uint32_t price_type_;
    ::uint32_t price_;
    ::uint32_t limit_type_;
    ::uint32_t limit_amount_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_achiveactivityshop_2eproto;
};// -------------------------------------------------------------------

class achiveactivityshop_ConfigEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          achiveactivityshop_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achiveactivityshop,
          ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      achiveactivityshop_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achiveactivityshop,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  achiveactivityshop_ConfigEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR achiveactivityshop_ConfigEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit achiveactivityshop_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const achiveactivityshop_ConfigEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const achiveactivityshop_ConfigEntry_DoNotUse*>(
        &_achiveactivityshop_ConfigEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_achiveactivityshop_2eproto;
};
// -------------------------------------------------------------------

class PROTOBUF_API achiveactivityshop final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:achiveactivityshop) */ {
 public:
  inline achiveactivityshop() : achiveactivityshop(nullptr) {}
  ~achiveactivityshop() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR achiveactivityshop(::google::protobuf::internal::ConstantInitialized);

  inline achiveactivityshop(const achiveactivityshop& from)
      : achiveactivityshop(nullptr, from) {}
  achiveactivityshop(achiveactivityshop&& from) noexcept
    : achiveactivityshop() {
    *this = ::std::move(from);
  }

  inline achiveactivityshop& operator=(const achiveactivityshop& from) {
    CopyFrom(from);
    return *this;
  }
  inline achiveactivityshop& operator=(achiveactivityshop&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const achiveactivityshop& default_instance() {
    return *internal_default_instance();
  }
  static inline const achiveactivityshop* internal_default_instance() {
    return reinterpret_cast<const achiveactivityshop*>(
               &_achiveactivityshop_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(achiveactivityshop& a, achiveactivityshop& b) {
    a.Swap(&b);
  }
  inline void Swap(achiveactivityshop* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(achiveactivityshop* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  achiveactivityshop* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<achiveactivityshop>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const achiveactivityshop& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const achiveactivityshop& from) {
    achiveactivityshop::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(achiveactivityshop* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "achiveactivityshop";
  }
  protected:
  explicit achiveactivityshop(::google::protobuf::Arena* arena);
  achiveactivityshop(::google::protobuf::Arena* arena, const achiveactivityshop& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
  };
  // map<uint32, .DT_achiveactivityshop> config = 1;
  int config_size() const;
  private:
  int _internal_config_size() const;

  public:
  void clear_config() ;
  const ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>& config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>* mutable_config();

  private:
  const ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>& _internal_config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>* _internal_mutable_config();

  public:
  // @@protoc_insertion_point(class_scope:achiveactivityshop)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<achiveactivityshop_ConfigEntry_DoNotUse, ::uint32_t, ::DT_achiveactivityshop,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        config_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_achiveactivityshop_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DT_achiveactivityshop

// uint32 id = 1;
inline void DT_achiveactivityshop::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::id() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.id)
  return _internal_id();
}
inline void DT_achiveactivityshop::set_id(::uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.id)
}
inline ::uint32_t DT_achiveactivityshop::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void DT_achiveactivityshop::_internal_set_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_ = value;
}

// uint32 item_id = 2;
inline void DT_achiveactivityshop::clear_item_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.item_id_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::item_id() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.item_id)
  return _internal_item_id();
}
inline void DT_achiveactivityshop::set_item_id(::uint32_t value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.item_id)
}
inline ::uint32_t DT_achiveactivityshop::_internal_item_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.item_id_;
}
inline void DT_achiveactivityshop::_internal_set_item_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.item_id_ = value;
}

// uint32 shop_type = 3;
inline void DT_achiveactivityshop::clear_shop_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.shop_type_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::shop_type() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.shop_type)
  return _internal_shop_type();
}
inline void DT_achiveactivityshop::set_shop_type(::uint32_t value) {
  _internal_set_shop_type(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.shop_type)
}
inline ::uint32_t DT_achiveactivityshop::_internal_shop_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.shop_type_;
}
inline void DT_achiveactivityshop::_internal_set_shop_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.shop_type_ = value;
}

// uint32 req_type = 4;
inline void DT_achiveactivityshop::clear_req_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.req_type_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::req_type() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.req_type)
  return _internal_req_type();
}
inline void DT_achiveactivityshop::set_req_type(::uint32_t value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.req_type)
}
inline ::uint32_t DT_achiveactivityshop::_internal_req_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.req_type_;
}
inline void DT_achiveactivityshop::_internal_set_req_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.req_type_ = value;
}

// uint32 event_id = 5;
inline void DT_achiveactivityshop::clear_event_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.event_id_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::event_id() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.event_id)
  return _internal_event_id();
}
inline void DT_achiveactivityshop::set_event_id(::uint32_t value) {
  _internal_set_event_id(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.event_id)
}
inline ::uint32_t DT_achiveactivityshop::_internal_event_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.event_id_;
}
inline void DT_achiveactivityshop::_internal_set_event_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.event_id_ = value;
}

// uint32 req_1 = 6;
inline void DT_achiveactivityshop::clear_req_1() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.req_1_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::req_1() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.req_1)
  return _internal_req_1();
}
inline void DT_achiveactivityshop::set_req_1(::uint32_t value) {
  _internal_set_req_1(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.req_1)
}
inline ::uint32_t DT_achiveactivityshop::_internal_req_1() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.req_1_;
}
inline void DT_achiveactivityshop::_internal_set_req_1(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.req_1_ = value;
}

// uint32 req_2 = 7;
inline void DT_achiveactivityshop::clear_req_2() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.req_2_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::req_2() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.req_2)
  return _internal_req_2();
}
inline void DT_achiveactivityshop::set_req_2(::uint32_t value) {
  _internal_set_req_2(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.req_2)
}
inline ::uint32_t DT_achiveactivityshop::_internal_req_2() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.req_2_;
}
inline void DT_achiveactivityshop::_internal_set_req_2(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.req_2_ = value;
}

// uint32 price_type = 8;
inline void DT_achiveactivityshop::clear_price_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.price_type_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::price_type() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.price_type)
  return _internal_price_type();
}
inline void DT_achiveactivityshop::set_price_type(::uint32_t value) {
  _internal_set_price_type(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.price_type)
}
inline ::uint32_t DT_achiveactivityshop::_internal_price_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.price_type_;
}
inline void DT_achiveactivityshop::_internal_set_price_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.price_type_ = value;
}

// uint32 price = 9;
inline void DT_achiveactivityshop::clear_price() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.price_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::price() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.price)
  return _internal_price();
}
inline void DT_achiveactivityshop::set_price(::uint32_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.price)
}
inline ::uint32_t DT_achiveactivityshop::_internal_price() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.price_;
}
inline void DT_achiveactivityshop::_internal_set_price(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.price_ = value;
}

// uint32 limit_type = 10;
inline void DT_achiveactivityshop::clear_limit_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.limit_type_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::limit_type() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.limit_type)
  return _internal_limit_type();
}
inline void DT_achiveactivityshop::set_limit_type(::uint32_t value) {
  _internal_set_limit_type(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.limit_type)
}
inline ::uint32_t DT_achiveactivityshop::_internal_limit_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.limit_type_;
}
inline void DT_achiveactivityshop::_internal_set_limit_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.limit_type_ = value;
}

// uint32 limit_amount = 11;
inline void DT_achiveactivityshop::clear_limit_amount() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.limit_amount_ = 0u;
}
inline ::uint32_t DT_achiveactivityshop::limit_amount() const {
  // @@protoc_insertion_point(field_get:DT_achiveactivityshop.limit_amount)
  return _internal_limit_amount();
}
inline void DT_achiveactivityshop::set_limit_amount(::uint32_t value) {
  _internal_set_limit_amount(value);
  // @@protoc_insertion_point(field_set:DT_achiveactivityshop.limit_amount)
}
inline ::uint32_t DT_achiveactivityshop::_internal_limit_amount() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.limit_amount_;
}
inline void DT_achiveactivityshop::_internal_set_limit_amount(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.limit_amount_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// achiveactivityshop

// map<uint32, .DT_achiveactivityshop> config = 1;
inline int achiveactivityshop::_internal_config_size() const {
  return _internal_config().size();
}
inline int achiveactivityshop::config_size() const {
  return _internal_config_size();
}
inline void achiveactivityshop::clear_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.config_.Clear();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>& achiveactivityshop::_internal_config() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.config_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>& achiveactivityshop::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:achiveactivityshop.config)
  return _internal_config();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>* achiveactivityshop::_internal_mutable_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.config_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>* achiveactivityshop::mutable_config() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:achiveactivityshop.config)
  return _internal_mutable_config();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_achiveactivityshop_2eproto_2epb_2eh
