// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: achiveactivityshop.proto

#include "achiveactivityshop.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
//PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr DT_achiveactivityshop::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0u},
        item_id_{0u},
        shop_type_{0u},
        req_type_{0u},
        event_id_{0u},
        req_1_{0u},
        req_2_{0u},
        price_type_{0u},
        price_{0u},
        limit_type_{0u},
        limit_amount_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DT_achiveactivityshop::DT_achiveactivityshop(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DT_achiveactivityshopDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DT_achiveactivityshopDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DT_achiveactivityshopDefaultTypeInternal() {}
  union {
    DT_achiveactivityshop _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DT_achiveactivityshopDefaultTypeInternal _DT_achiveactivityshop_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR achiveactivityshop_ConfigEntry_DoNotUse::achiveactivityshop_ConfigEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal() {}
  union {
    achiveactivityshop_ConfigEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 achiveactivityshop_ConfigEntry_DoNotUseDefaultTypeInternal _achiveactivityshop_ConfigEntry_DoNotUse_default_instance_;

inline constexpr achiveactivityshop::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR achiveactivityshop::achiveactivityshop(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct achiveactivityshopDefaultTypeInternal {
  PROTOBUF_CONSTEXPR achiveactivityshopDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~achiveactivityshopDefaultTypeInternal() {}
  union {
    achiveactivityshop _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 achiveactivityshopDefaultTypeInternal _achiveactivityshop_default_instance_;
static ::_pb::Metadata file_level_metadata_achiveactivityshop_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_achiveactivityshop_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_achiveactivityshop_2eproto = nullptr;
const ::uint32_t TableStruct_achiveactivityshop_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.item_id_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.shop_type_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.req_type_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.event_id_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.req_1_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.req_2_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.price_type_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.price_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.limit_type_),
    PROTOBUF_FIELD_OFFSET(::DT_achiveactivityshop, _impl_.limit_amount_),
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop_ConfigEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop_ConfigEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop_ConfigEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop_ConfigEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::achiveactivityshop, _impl_.config_),
};

static const ::_pbi::MigrationSchema
    schemas_achiveactivityshop[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::DT_achiveactivityshop)},
        {19, 29, -1, sizeof(::achiveactivityshop_ConfigEntry_DoNotUse)},
        {31, -1, -1, sizeof(::achiveactivityshop)},
};

static const ::_pb::Message* const file_default_instances_achiveactivityshop[] = {
    &::_DT_achiveactivityshop_default_instance_._instance,
    &::_achiveactivityshop_ConfigEntry_DoNotUse_default_instance_._instance,
    &::_achiveactivityshop_default_instance_._instance,
};
const char descriptor_table_protodef_achiveactivityshop_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\030achiveactivityshop.proto\"\326\001\n\025DT_achive"
    "activityshop\022\n\n\002id\030\001 \001(\r\022\017\n\007item_id\030\002 \001("
    "\r\022\021\n\tshop_type\030\003 \001(\r\022\020\n\010req_type\030\004 \001(\r\022\020"
    "\n\010event_id\030\005 \001(\r\022\r\n\005req_1\030\006 \001(\r\022\r\n\005req_2"
    "\030\007 \001(\r\022\022\n\nprice_type\030\010 \001(\r\022\r\n\005price\030\t \001("
    "\r\022\022\n\nlimit_type\030\n \001(\r\022\024\n\014limit_amount\030\013 "
    "\001(\r\"\214\001\n\022achiveactivityshop\022/\n\006config\030\001 \003"
    "(\0132\037.achiveactivityshop.ConfigEntry\032E\n\013C"
    "onfigEntry\022\013\n\003key\030\001 \001(\r\022%\n\005value\030\002 \001(\0132\026"
    ".DT_achiveactivityshop:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_achiveactivityshop_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_achiveactivityshop_2eproto = {
    false,
    false,
    394,
    descriptor_table_protodef_achiveactivityshop_2eproto,
    "achiveactivityshop.proto",
    &descriptor_table_achiveactivityshop_2eproto_once,
    nullptr,
    0,
    3,
    schemas_achiveactivityshop,
    file_default_instances_achiveactivityshop,
    TableStruct_achiveactivityshop_2eproto::offsets,
    file_level_metadata_achiveactivityshop_2eproto,
    file_level_enum_descriptors_achiveactivityshop_2eproto,
    file_level_service_descriptors_achiveactivityshop_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_achiveactivityshop_2eproto_getter() {
  return &descriptor_table_achiveactivityshop_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_achiveactivityshop_2eproto(&descriptor_table_achiveactivityshop_2eproto);
// ===================================================================

class DT_achiveactivityshop::_Internal {
 public:
};

DT_achiveactivityshop::DT_achiveactivityshop(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DT_achiveactivityshop)
}
DT_achiveactivityshop::DT_achiveactivityshop(
    ::google::protobuf::Arena* arena, const DT_achiveactivityshop& from)
    : DT_achiveactivityshop(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DT_achiveactivityshop::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DT_achiveactivityshop::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, limit_amount_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::limit_amount_));
}
DT_achiveactivityshop::~DT_achiveactivityshop() {
  // @@protoc_insertion_point(destructor:DT_achiveactivityshop)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DT_achiveactivityshop::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DT_achiveactivityshop::Clear() {
// @@protoc_insertion_point(message_clear_start:DT_achiveactivityshop)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.limit_amount_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.limit_amount_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DT_achiveactivityshop::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 0, 0, 2> DT_achiveactivityshop::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DT_achiveactivityshop_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.id_)}},
    // uint32 item_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.item_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.item_id_)}},
    // uint32 shop_type = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.shop_type_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.shop_type_)}},
    // uint32 req_type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.req_type_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_type_)}},
    // uint32 event_id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.event_id_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.event_id_)}},
    // uint32 req_1 = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.req_1_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_1_)}},
    // uint32 req_2 = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.req_2_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_2_)}},
    // uint32 price_type = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.price_type_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.price_type_)}},
    // uint32 price = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.price_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.price_)}},
    // uint32 limit_type = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.limit_type_), 63>(),
     {80, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.limit_type_)}},
    // uint32 limit_amount = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_achiveactivityshop, _impl_.limit_amount_), 63>(),
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.limit_amount_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 item_id = 2;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.item_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 shop_type = 3;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.shop_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 req_type = 4;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 event_id = 5;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.event_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 req_1 = 6;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 req_2 = 7;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.req_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 price_type = 8;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.price_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 price = 9;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.price_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 limit_type = 10;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.limit_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 limit_amount = 11;
    {PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.limit_amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DT_achiveactivityshop::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DT_achiveactivityshop)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // uint32 item_id = 2;
  if (this->_internal_item_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_item_id(), target);
  }

  // uint32 shop_type = 3;
  if (this->_internal_shop_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_shop_type(), target);
  }

  // uint32 req_type = 4;
  if (this->_internal_req_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_req_type(), target);
  }

  // uint32 event_id = 5;
  if (this->_internal_event_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_event_id(), target);
  }

  // uint32 req_1 = 6;
  if (this->_internal_req_1() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_req_1(), target);
  }

  // uint32 req_2 = 7;
  if (this->_internal_req_2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_req_2(), target);
  }

  // uint32 price_type = 8;
  if (this->_internal_price_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        8, this->_internal_price_type(), target);
  }

  // uint32 price = 9;
  if (this->_internal_price() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        9, this->_internal_price(), target);
  }

  // uint32 limit_type = 10;
  if (this->_internal_limit_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        10, this->_internal_limit_type(), target);
  }

  // uint32 limit_amount = 11;
  if (this->_internal_limit_amount() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        11, this->_internal_limit_amount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DT_achiveactivityshop)
  return target;
}

::size_t DT_achiveactivityshop::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DT_achiveactivityshop)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 item_id = 2;
  if (this->_internal_item_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_item_id());
  }

  // uint32 shop_type = 3;
  if (this->_internal_shop_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_shop_type());
  }

  // uint32 req_type = 4;
  if (this->_internal_req_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_req_type());
  }

  // uint32 event_id = 5;
  if (this->_internal_event_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_event_id());
  }

  // uint32 req_1 = 6;
  if (this->_internal_req_1() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_req_1());
  }

  // uint32 req_2 = 7;
  if (this->_internal_req_2() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_req_2());
  }

  // uint32 price_type = 8;
  if (this->_internal_price_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_price_type());
  }

  // uint32 price = 9;
  if (this->_internal_price() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_price());
  }

  // uint32 limit_type = 10;
  if (this->_internal_limit_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_limit_type());
  }

  // uint32 limit_amount = 11;
  if (this->_internal_limit_amount() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_limit_amount());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DT_achiveactivityshop::_class_data_ = {
    DT_achiveactivityshop::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DT_achiveactivityshop::GetClassData() const {
  return &_class_data_;
}

void DT_achiveactivityshop::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DT_achiveactivityshop*>(&to_msg);
  auto& from = static_cast<const DT_achiveactivityshop&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DT_achiveactivityshop)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_item_id() != 0) {
    _this->_internal_set_item_id(from._internal_item_id());
  }
  if (from._internal_shop_type() != 0) {
    _this->_internal_set_shop_type(from._internal_shop_type());
  }
  if (from._internal_req_type() != 0) {
    _this->_internal_set_req_type(from._internal_req_type());
  }
  if (from._internal_event_id() != 0) {
    _this->_internal_set_event_id(from._internal_event_id());
  }
  if (from._internal_req_1() != 0) {
    _this->_internal_set_req_1(from._internal_req_1());
  }
  if (from._internal_req_2() != 0) {
    _this->_internal_set_req_2(from._internal_req_2());
  }
  if (from._internal_price_type() != 0) {
    _this->_internal_set_price_type(from._internal_price_type());
  }
  if (from._internal_price() != 0) {
    _this->_internal_set_price(from._internal_price());
  }
  if (from._internal_limit_type() != 0) {
    _this->_internal_set_limit_type(from._internal_limit_type());
  }
  if (from._internal_limit_amount() != 0) {
    _this->_internal_set_limit_amount(from._internal_limit_amount());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DT_achiveactivityshop::CopyFrom(const DT_achiveactivityshop& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DT_achiveactivityshop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DT_achiveactivityshop::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DT_achiveactivityshop::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DT_achiveactivityshop::InternalSwap(DT_achiveactivityshop* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.limit_amount_)
      + sizeof(DT_achiveactivityshop::_impl_.limit_amount_)
      - PROTOBUF_FIELD_OFFSET(DT_achiveactivityshop, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata DT_achiveactivityshop::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achiveactivityshop_2eproto_getter, &descriptor_table_achiveactivityshop_2eproto_once,
      file_level_metadata_achiveactivityshop_2eproto[0]);
}
// ===================================================================

achiveactivityshop_ConfigEntry_DoNotUse::achiveactivityshop_ConfigEntry_DoNotUse() {}
achiveactivityshop_ConfigEntry_DoNotUse::achiveactivityshop_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata achiveactivityshop_ConfigEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achiveactivityshop_2eproto_getter, &descriptor_table_achiveactivityshop_2eproto_once,
      file_level_metadata_achiveactivityshop_2eproto[1]);
}
// ===================================================================

class achiveactivityshop::_Internal {
 public:
};

achiveactivityshop::achiveactivityshop(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:achiveactivityshop)
}
inline PROTOBUF_NDEBUG_INLINE achiveactivityshop::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : config_{visibility, arena, from.config_},
        _cached_size_{0} {}

achiveactivityshop::achiveactivityshop(
    ::google::protobuf::Arena* arena,
    const achiveactivityshop& from)
    : ::google::protobuf::Message(arena) {
  achiveactivityshop* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:achiveactivityshop)
}
inline PROTOBUF_NDEBUG_INLINE achiveactivityshop::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : config_{visibility, arena},
        _cached_size_{0} {}

inline void achiveactivityshop::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
achiveactivityshop::~achiveactivityshop() {
  // @@protoc_insertion_point(destructor:achiveactivityshop)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void achiveactivityshop::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void achiveactivityshop::Clear() {
// @@protoc_insertion_point(message_clear_start:achiveactivityshop)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* achiveactivityshop::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2> achiveactivityshop::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_achiveactivityshop_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<uint32, .DT_achiveactivityshop> config = 1;
    {PROTOBUF_FIELD_OFFSET(achiveactivityshop, _impl_.config_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(achiveactivityshop()._impl_.config_)>(
        1, 0, 0, 13,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::DT_achiveactivityshop>},
  }}, {{
  }},
};

::uint8_t* achiveactivityshop::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:achiveactivityshop)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<uint32, .DT_achiveactivityshop> config = 1;
  if (!_internal_config().empty()) {
    using MapType = ::google::protobuf::Map<::uint32_t, ::DT_achiveactivityshop>;
    using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::DT_achiveactivityshop,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_config();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:achiveactivityshop)
  return target;
}

::size_t achiveactivityshop::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:achiveactivityshop)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, .DT_achiveactivityshop> config = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_config_size());
  for (const auto& entry : _internal_config()) {
    total_size += _pbi::MapEntryFuncs<::uint32_t, ::DT_achiveactivityshop,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData achiveactivityshop::_class_data_ = {
    achiveactivityshop::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* achiveactivityshop::GetClassData() const {
  return &_class_data_;
}

void achiveactivityshop::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<achiveactivityshop*>(&to_msg);
  auto& from = static_cast<const achiveactivityshop&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:achiveactivityshop)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.config_.MergeFrom(from._impl_.config_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void achiveactivityshop::CopyFrom(const achiveactivityshop& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:achiveactivityshop)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool achiveactivityshop::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* achiveactivityshop::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void achiveactivityshop::InternalSwap(achiveactivityshop* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.config_.InternalSwap(&other->_impl_.config_);
}

::google::protobuf::Metadata achiveactivityshop::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_achiveactivityshop_2eproto_getter, &descriptor_table_achiveactivityshop_2eproto_once,
      file_level_metadata_achiveactivityshop_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
