// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: additionattr.proto

#include "additionattr.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
//PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr DT_additionattr::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_{0u},
        add_type_{0u},
        add_value_{0u},
        add_ratio_{0u},
        add_extra_value_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DT_additionattr::DT_additionattr(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DT_additionattrDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DT_additionattrDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DT_additionattrDefaultTypeInternal() {}
  union {
    DT_additionattr _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DT_additionattrDefaultTypeInternal _DT_additionattr_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR additionattr_ConfigEntry_DoNotUse::additionattr_ConfigEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct additionattr_ConfigEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR additionattr_ConfigEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~additionattr_ConfigEntry_DoNotUseDefaultTypeInternal() {}
  union {
    additionattr_ConfigEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 additionattr_ConfigEntry_DoNotUseDefaultTypeInternal _additionattr_ConfigEntry_DoNotUse_default_instance_;

inline constexpr additionattr::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : config_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR additionattr::additionattr(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct additionattrDefaultTypeInternal {
  PROTOBUF_CONSTEXPR additionattrDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~additionattrDefaultTypeInternal() {}
  union {
    additionattr _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_API
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 additionattrDefaultTypeInternal _additionattr_default_instance_;
static ::_pb::Metadata file_level_metadata_additionattr_2eproto[3];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_additionattr_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_additionattr_2eproto = nullptr;
const ::uint32_t TableStruct_additionattr_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _impl_.add_type_),
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _impl_.add_value_),
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _impl_.add_ratio_),
    PROTOBUF_FIELD_OFFSET(::DT_additionattr, _impl_.add_extra_value_),
    PROTOBUF_FIELD_OFFSET(::additionattr_ConfigEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::additionattr_ConfigEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::additionattr_ConfigEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::additionattr_ConfigEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::additionattr, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::additionattr, _impl_.config_),
};

static const ::_pbi::MigrationSchema
    schemas_additionattr[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::DT_additionattr)},
        {13, 23, -1, sizeof(::additionattr_ConfigEntry_DoNotUse)},
        {25, -1, -1, sizeof(::additionattr)},
};

static const ::_pb::Message* const file_default_instances_additionattr[] = {
    &::_DT_additionattr_default_instance_._instance,
    &::_additionattr_ConfigEntry_DoNotUse_default_instance_._instance,
    &::_additionattr_default_instance_._instance,
};
const char descriptor_table_protodef_additionattr_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\022additionattr.proto\"n\n\017DT_additionattr\022"
    "\n\n\002id\030\001 \001(\r\022\020\n\010add_type\030\002 \001(\r\022\021\n\tadd_val"
    "ue\030\003 \001(\r\022\021\n\tadd_ratio\030\004 \001(\r\022\027\n\017add_extra"
    "_value\030\005 \001(\r\"z\n\014additionattr\022)\n\006config\030\001"
    " \003(\0132\031.additionattr.ConfigEntry\032\?\n\013Confi"
    "gEntry\022\013\n\003key\030\001 \001(\r\022\037\n\005value\030\002 \001(\0132\020.DT_"
    "additionattr:\0028\001b\006proto3"
};
static ::absl::once_flag descriptor_table_additionattr_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_additionattr_2eproto = {
    false,
    false,
    264,
    descriptor_table_protodef_additionattr_2eproto,
    "additionattr.proto",
    &descriptor_table_additionattr_2eproto_once,
    nullptr,
    0,
    3,
    schemas_additionattr,
    file_default_instances_additionattr,
    TableStruct_additionattr_2eproto::offsets,
    file_level_metadata_additionattr_2eproto,
    file_level_enum_descriptors_additionattr_2eproto,
    file_level_service_descriptors_additionattr_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_additionattr_2eproto_getter() {
  return &descriptor_table_additionattr_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_additionattr_2eproto(&descriptor_table_additionattr_2eproto);
// ===================================================================

class DT_additionattr::_Internal {
 public:
};

DT_additionattr::DT_additionattr(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DT_additionattr)
}
DT_additionattr::DT_additionattr(
    ::google::protobuf::Arena* arena, const DT_additionattr& from)
    : DT_additionattr(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DT_additionattr::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DT_additionattr::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, add_extra_value_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::add_extra_value_));
}
DT_additionattr::~DT_additionattr() {
  // @@protoc_insertion_point(destructor:DT_additionattr)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DT_additionattr::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void DT_additionattr::Clear() {
// @@protoc_insertion_point(message_clear_start:DT_additionattr)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.add_extra_value_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.add_extra_value_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* DT_additionattr::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> DT_additionattr::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DT_additionattr_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_additionattr, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.id_)}},
    // uint32 add_type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_additionattr, _impl_.add_type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_type_)}},
    // uint32 add_value = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_additionattr, _impl_.add_value_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_value_)}},
    // uint32 add_ratio = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_additionattr, _impl_.add_ratio_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_ratio_)}},
    // uint32 add_extra_value = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DT_additionattr, _impl_.add_extra_value_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_extra_value_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 add_type = 2;
    {PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 add_value = 3;
    {PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 add_ratio = 4;
    {PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_ratio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 add_extra_value = 5;
    {PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_extra_value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* DT_additionattr::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DT_additionattr)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_id(), target);
  }

  // uint32 add_type = 2;
  if (this->_internal_add_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_add_type(), target);
  }

  // uint32 add_value = 3;
  if (this->_internal_add_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_add_value(), target);
  }

  // uint32 add_ratio = 4;
  if (this->_internal_add_ratio() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_add_ratio(), target);
  }

  // uint32 add_extra_value = 5;
  if (this->_internal_add_extra_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_add_extra_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DT_additionattr)
  return target;
}

::size_t DT_additionattr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DT_additionattr)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_id());
  }

  // uint32 add_type = 2;
  if (this->_internal_add_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_add_type());
  }

  // uint32 add_value = 3;
  if (this->_internal_add_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_add_value());
  }

  // uint32 add_ratio = 4;
  if (this->_internal_add_ratio() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_add_ratio());
  }

  // uint32 add_extra_value = 5;
  if (this->_internal_add_extra_value() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_add_extra_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData DT_additionattr::_class_data_ = {
    DT_additionattr::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* DT_additionattr::GetClassData() const {
  return &_class_data_;
}

void DT_additionattr::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<DT_additionattr*>(&to_msg);
  auto& from = static_cast<const DT_additionattr&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DT_additionattr)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_add_type() != 0) {
    _this->_internal_set_add_type(from._internal_add_type());
  }
  if (from._internal_add_value() != 0) {
    _this->_internal_set_add_value(from._internal_add_value());
  }
  if (from._internal_add_ratio() != 0) {
    _this->_internal_set_add_ratio(from._internal_add_ratio());
  }
  if (from._internal_add_extra_value() != 0) {
    _this->_internal_set_add_extra_value(from._internal_add_extra_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DT_additionattr::CopyFrom(const DT_additionattr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DT_additionattr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DT_additionattr::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* DT_additionattr::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void DT_additionattr::InternalSwap(DT_additionattr* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.add_extra_value_)
      + sizeof(DT_additionattr::_impl_.add_extra_value_)
      - PROTOBUF_FIELD_OFFSET(DT_additionattr, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata DT_additionattr::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_additionattr_2eproto_getter, &descriptor_table_additionattr_2eproto_once,
      file_level_metadata_additionattr_2eproto[0]);
}
// ===================================================================

additionattr_ConfigEntry_DoNotUse::additionattr_ConfigEntry_DoNotUse() {}
additionattr_ConfigEntry_DoNotUse::additionattr_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata additionattr_ConfigEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_additionattr_2eproto_getter, &descriptor_table_additionattr_2eproto_once,
      file_level_metadata_additionattr_2eproto[1]);
}
// ===================================================================

class additionattr::_Internal {
 public:
};

additionattr::additionattr(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:additionattr)
}
inline PROTOBUF_NDEBUG_INLINE additionattr::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : config_{visibility, arena, from.config_},
        _cached_size_{0} {}

additionattr::additionattr(
    ::google::protobuf::Arena* arena,
    const additionattr& from)
    : ::google::protobuf::Message(arena) {
  additionattr* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:additionattr)
}
inline PROTOBUF_NDEBUG_INLINE additionattr::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : config_{visibility, arena},
        _cached_size_{0} {}

inline void additionattr::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
additionattr::~additionattr() {
  // @@protoc_insertion_point(destructor:additionattr)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void additionattr::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void additionattr::Clear() {
// @@protoc_insertion_point(message_clear_start:additionattr)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.config_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* additionattr::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 0, 2> additionattr::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_additionattr_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<uint32, .DT_additionattr> config = 1;
    {PROTOBUF_FIELD_OFFSET(additionattr, _impl_.config_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(additionattr()._impl_.config_)>(
        1, 0, 0, 13,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::DT_additionattr>},
  }}, {{
  }},
};

::uint8_t* additionattr::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:additionattr)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<uint32, .DT_additionattr> config = 1;
  if (!_internal_config().empty()) {
    using MapType = ::google::protobuf::Map<::uint32_t, ::DT_additionattr>;
    using WireHelper = _pbi::MapEntryFuncs<::uint32_t, ::DT_additionattr,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_config();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:additionattr)
  return target;
}

::size_t additionattr::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:additionattr)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, .DT_additionattr> config = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_config_size());
  for (const auto& entry : _internal_config()) {
    total_size += _pbi::MapEntryFuncs<::uint32_t, ::DT_additionattr,
                                   _pbi::WireFormatLite::TYPE_UINT32,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData additionattr::_class_data_ = {
    additionattr::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* additionattr::GetClassData() const {
  return &_class_data_;
}

void additionattr::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<additionattr*>(&to_msg);
  auto& from = static_cast<const additionattr&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:additionattr)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.config_.MergeFrom(from._impl_.config_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void additionattr::CopyFrom(const additionattr& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:additionattr)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool additionattr::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* additionattr::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void additionattr::InternalSwap(additionattr* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.config_.InternalSwap(&other->_impl_.config_);
}

::google::protobuf::Metadata additionattr::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_additionattr_2eproto_getter, &descriptor_table_additionattr_2eproto_once,
      file_level_metadata_additionattr_2eproto[2]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
