// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: additionattr.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_additionattr_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_additionattr_2eproto_2epb_2eh

#include "ProtobufExport.h"
#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_additionattr_2eproto PROTOBUF_API

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct PROTOBUF_API TableStruct_additionattr_2eproto {
  static const ::uint32_t offsets[];
};
PROTOBUF_API extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_additionattr_2eproto;
class DT_additionattr;
struct DT_additionattrDefaultTypeInternal;
PROTOBUF_API extern DT_additionattrDefaultTypeInternal _DT_additionattr_default_instance_;
class additionattr;
struct additionattrDefaultTypeInternal;
PROTOBUF_API extern additionattrDefaultTypeInternal _additionattr_default_instance_;
class additionattr_ConfigEntry_DoNotUse;
struct additionattr_ConfigEntry_DoNotUseDefaultTypeInternal;
PROTOBUF_API extern additionattr_ConfigEntry_DoNotUseDefaultTypeInternal _additionattr_ConfigEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PROTOBUF_API DT_additionattr final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DT_additionattr) */ {
 public:
  inline DT_additionattr() : DT_additionattr(nullptr) {}
  ~DT_additionattr() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR DT_additionattr(::google::protobuf::internal::ConstantInitialized);

  inline DT_additionattr(const DT_additionattr& from)
      : DT_additionattr(nullptr, from) {}
  DT_additionattr(DT_additionattr&& from) noexcept
    : DT_additionattr() {
    *this = ::std::move(from);
  }

  inline DT_additionattr& operator=(const DT_additionattr& from) {
    CopyFrom(from);
    return *this;
  }
  inline DT_additionattr& operator=(DT_additionattr&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DT_additionattr& default_instance() {
    return *internal_default_instance();
  }
  static inline const DT_additionattr* internal_default_instance() {
    return reinterpret_cast<const DT_additionattr*>(
               &_DT_additionattr_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DT_additionattr& a, DT_additionattr& b) {
    a.Swap(&b);
  }
  inline void Swap(DT_additionattr* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DT_additionattr* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DT_additionattr* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DT_additionattr>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DT_additionattr& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const DT_additionattr& from) {
    DT_additionattr::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DT_additionattr* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "DT_additionattr";
  }
  protected:
  explicit DT_additionattr(::google::protobuf::Arena* arena);
  DT_additionattr(::google::protobuf::Arena* arena, const DT_additionattr& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kAddTypeFieldNumber = 2,
    kAddValueFieldNumber = 3,
    kAddRatioFieldNumber = 4,
    kAddExtraValueFieldNumber = 5,
  };
  // uint32 id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 add_type = 2;
  void clear_add_type() ;
  ::uint32_t add_type() const;
  void set_add_type(::uint32_t value);

  private:
  ::uint32_t _internal_add_type() const;
  void _internal_set_add_type(::uint32_t value);

  public:
  // uint32 add_value = 3;
  void clear_add_value() ;
  ::uint32_t add_value() const;
  void set_add_value(::uint32_t value);

  private:
  ::uint32_t _internal_add_value() const;
  void _internal_set_add_value(::uint32_t value);

  public:
  // uint32 add_ratio = 4;
  void clear_add_ratio() ;
  ::uint32_t add_ratio() const;
  void set_add_ratio(::uint32_t value);

  private:
  ::uint32_t _internal_add_ratio() const;
  void _internal_set_add_ratio(::uint32_t value);

  public:
  // uint32 add_extra_value = 5;
  void clear_add_extra_value() ;
  ::uint32_t add_extra_value() const;
  void set_add_extra_value(::uint32_t value);

  private:
  ::uint32_t _internal_add_extra_value() const;
  void _internal_set_add_extra_value(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DT_additionattr)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::uint32_t id_;
    ::uint32_t add_type_;
    ::uint32_t add_value_;
    ::uint32_t add_ratio_;
    ::uint32_t add_extra_value_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_additionattr_2eproto;
};// -------------------------------------------------------------------

class additionattr_ConfigEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          additionattr_ConfigEntry_DoNotUse, ::uint32_t, ::DT_additionattr,
          ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
          ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      additionattr_ConfigEntry_DoNotUse, ::uint32_t, ::DT_additionattr,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  additionattr_ConfigEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR additionattr_ConfigEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit additionattr_ConfigEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const additionattr_ConfigEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const additionattr_ConfigEntry_DoNotUse*>(
        &_additionattr_ConfigEntry_DoNotUse_default_instance_);
  }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  ::google::protobuf::Metadata GetMetadata() const final;
  friend struct ::TableStruct_additionattr_2eproto;
};
// -------------------------------------------------------------------

class PROTOBUF_API additionattr final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:additionattr) */ {
 public:
  inline additionattr() : additionattr(nullptr) {}
  ~additionattr() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR additionattr(::google::protobuf::internal::ConstantInitialized);

  inline additionattr(const additionattr& from)
      : additionattr(nullptr, from) {}
  additionattr(additionattr&& from) noexcept
    : additionattr() {
    *this = ::std::move(from);
  }

  inline additionattr& operator=(const additionattr& from) {
    CopyFrom(from);
    return *this;
  }
  inline additionattr& operator=(additionattr&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const additionattr& default_instance() {
    return *internal_default_instance();
  }
  static inline const additionattr* internal_default_instance() {
    return reinterpret_cast<const additionattr*>(
               &_additionattr_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(additionattr& a, additionattr& b) {
    a.Swap(&b);
  }
  inline void Swap(additionattr* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(additionattr* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  additionattr* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<additionattr>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const additionattr& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const additionattr& from) {
    additionattr::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(additionattr* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "additionattr";
  }
  protected:
  explicit additionattr(::google::protobuf::Arena* arena);
  additionattr(::google::protobuf::Arena* arena, const additionattr& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
  };
  // map<uint32, .DT_additionattr> config = 1;
  int config_size() const;
  private:
  int _internal_config_size() const;

  public:
  void clear_config() ;
  const ::google::protobuf::Map<::uint32_t, ::DT_additionattr>& config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_additionattr>* mutable_config();

  private:
  const ::google::protobuf::Map<::uint32_t, ::DT_additionattr>& _internal_config() const;
  ::google::protobuf::Map<::uint32_t, ::DT_additionattr>* _internal_mutable_config();

  public:
  // @@protoc_insertion_point(class_scope:additionattr)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 2,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct PROTOBUF_API Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::MapField<additionattr_ConfigEntry_DoNotUse, ::uint32_t, ::DT_additionattr,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        config_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_additionattr_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DT_additionattr

// uint32 id = 1;
inline void DT_additionattr::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = 0u;
}
inline ::uint32_t DT_additionattr::id() const {
  // @@protoc_insertion_point(field_get:DT_additionattr.id)
  return _internal_id();
}
inline void DT_additionattr::set_id(::uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:DT_additionattr.id)
}
inline ::uint32_t DT_additionattr::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void DT_additionattr::_internal_set_id(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_ = value;
}

// uint32 add_type = 2;
inline void DT_additionattr::clear_add_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.add_type_ = 0u;
}
inline ::uint32_t DT_additionattr::add_type() const {
  // @@protoc_insertion_point(field_get:DT_additionattr.add_type)
  return _internal_add_type();
}
inline void DT_additionattr::set_add_type(::uint32_t value) {
  _internal_set_add_type(value);
  // @@protoc_insertion_point(field_set:DT_additionattr.add_type)
}
inline ::uint32_t DT_additionattr::_internal_add_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.add_type_;
}
inline void DT_additionattr::_internal_set_add_type(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.add_type_ = value;
}

// uint32 add_value = 3;
inline void DT_additionattr::clear_add_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.add_value_ = 0u;
}
inline ::uint32_t DT_additionattr::add_value() const {
  // @@protoc_insertion_point(field_get:DT_additionattr.add_value)
  return _internal_add_value();
}
inline void DT_additionattr::set_add_value(::uint32_t value) {
  _internal_set_add_value(value);
  // @@protoc_insertion_point(field_set:DT_additionattr.add_value)
}
inline ::uint32_t DT_additionattr::_internal_add_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.add_value_;
}
inline void DT_additionattr::_internal_set_add_value(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.add_value_ = value;
}

// uint32 add_ratio = 4;
inline void DT_additionattr::clear_add_ratio() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.add_ratio_ = 0u;
}
inline ::uint32_t DT_additionattr::add_ratio() const {
  // @@protoc_insertion_point(field_get:DT_additionattr.add_ratio)
  return _internal_add_ratio();
}
inline void DT_additionattr::set_add_ratio(::uint32_t value) {
  _internal_set_add_ratio(value);
  // @@protoc_insertion_point(field_set:DT_additionattr.add_ratio)
}
inline ::uint32_t DT_additionattr::_internal_add_ratio() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.add_ratio_;
}
inline void DT_additionattr::_internal_set_add_ratio(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.add_ratio_ = value;
}

// uint32 add_extra_value = 5;
inline void DT_additionattr::clear_add_extra_value() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.add_extra_value_ = 0u;
}
inline ::uint32_t DT_additionattr::add_extra_value() const {
  // @@protoc_insertion_point(field_get:DT_additionattr.add_extra_value)
  return _internal_add_extra_value();
}
inline void DT_additionattr::set_add_extra_value(::uint32_t value) {
  _internal_set_add_extra_value(value);
  // @@protoc_insertion_point(field_set:DT_additionattr.add_extra_value)
}
inline ::uint32_t DT_additionattr::_internal_add_extra_value() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.add_extra_value_;
}
inline void DT_additionattr::_internal_set_add_extra_value(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.add_extra_value_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// additionattr

// map<uint32, .DT_additionattr> config = 1;
inline int additionattr::_internal_config_size() const {
  return _internal_config().size();
}
inline int additionattr::config_size() const {
  return _internal_config_size();
}
inline void additionattr::clear_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.config_.Clear();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_additionattr>& additionattr::_internal_config() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.config_.GetMap();
}
inline const ::google::protobuf::Map<::uint32_t, ::DT_additionattr>& additionattr::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:additionattr.config)
  return _internal_config();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_additionattr>* additionattr::_internal_mutable_config() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.config_.MutableMap();
}
inline ::google::protobuf::Map<::uint32_t, ::DT_additionattr>* additionattr::mutable_config() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:additionattr.config)
  return _internal_mutable_config();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_additionattr_2eproto_2epb_2eh
